"""
XFaaS Test Harness - Partition Config Parser

Parses part-details.json generated by XFaaS after deployment.
"""

import json
from pathlib import Path
from dataclasses import dataclass
from typing import Optional


@dataclass
class Partition:
    """Represents a single partition in the workflow."""
    part_id: str
    csp: str
    region: str
    
    def get_resources_path(self, example_dir: Path) -> Path:
        """Get path to resources JSON for this partition."""
        return (
            example_dir / "partitions" / f"{self.csp}-{self.region}-{self.part_id}" 
            / "build" / "workflow" / "resources" 
            / f"{self.csp}-{self.region}-{self.part_id}.json"
        )


@dataclass
class PartitionConfig:
    """Parsed partition configuration from part-details.json."""
    order: list[str]  # Partition IDs in execution order
    partitions: dict[str, Partition]  # part_id -> Partition
    
    def get_start_partition(self) -> Partition:
        """Get the first partition (where workflow starts)."""
        return self.partitions[self.order[0]]
    
    def get_all_partitions(self) -> list[Partition]:
        """Get all partitions in order."""
        return [self.partitions[pid] for pid in self.order]


def parse_partition_config(example_dir: Path) -> Optional[PartitionConfig]:
    """
    Parse part-details.json from example directory.
    
    Args:
        example_dir: Path to example (e.g., tests/examples/asyncTester)
        
    Returns:
        PartitionConfig or None if file doesn't exist
    """
    part_details_path = example_dir / "partitions" / "part-details.json"
    
    if not part_details_path.exists():
        return None
    
    with open(part_details_path) as f:
        data = json.load(f)
    
    order = data.get("order", [])
    partitions = {}
    
    for part_id in order:
        if part_id in data:
            part_data = data[part_id]
            partitions[part_id] = Partition(
                part_id=part_id,
                csp=part_data["csp"],
                region=part_data["region"]
            )
    
    return PartitionConfig(order=order, partitions=partitions)


def resources_exist(example_dir: Path, partition: Partition) -> bool:
    """Check if resources JSON exists for a partition."""
    resources_path = partition.get_resources_path(example_dir)
    return resources_path.exists()
